# Adding library

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

# Load datasets

In [11]:
df=pd.read_csv("student_dataset_advanced.csv")
df.head(4)

,Student_ID,Name,Section,Parental_Education,Study_Hours_per_Day,Sleep_Hours,Attendance_Percentage,Internet_Access,Extra_Classes,Math_Marks,Science_Marks,English_Marks,Hindi_Marks,SST_Marks,Final_Score,Result,Grade
0,1,Amit Kumar Sharma_1,C,School,4.66,7.16,97.00,Yes,No,57.58,77.26,67.91,75.15,69.67,69.52,Pass,A
1,2,Rahul Singh Verma_2,A,Graduate,5.50,5.27,61.12,Yes,Yes,54.96,42.08,68.02,55.19,73.37,58.72,Pass,B
2,3,Priya Raj Yadav_3,C,Graduate,8.24,7.33,67.92,Yes,No,30.28,81.65,76.85,66.47,75.28,66.10,Pass,A
3,4,Sneha Dev Gupta_4,C,Graduate,4.55,6.53,75.87,Yes,Yes,52.92,43.52,51.51,65.35,62.68,55.20,Pass,B

In [3]:
df.shape

(10000, 17)

In [4]:
df.describe()

,Student_ID,Study_Hours_per_Day,Sleep_Hours,Attendance_Percentage,Math_Marks,Science_Marks,English_Marks,Hindi_Marks,SST_Marks,Final_Score
count,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,5000.50000,4.511813,6.489378,74.888959,59.943351,56.164564,65.244304,63.117776,57.508932,60.395759
std,2886.89568,1.474777,1.171050,14.337553,19.319434,19.848781,17.705603,18.976894,19.289791,13.882095
min,1.00000,1.000000,3.000000,40.000000,0.000000,0.000000,0.080000,0.000000,0.000000,13.460000
25%,2500.75000,3.500000,5.690000,65.110000,48.950000,42.257500,57.277500,53.475000,45.457500,57.970000
50%,5000.50000,4.520000,6.490000,75.035000,61.960000,56.970000,68.070000,65.575000,58.955000,63.715000
75%,7500.25000,5.530000,7.280000,85.242500,73.260000,70.162500,76.965000,76.112500,70.790000,68.930000
max,10000.00000,10.000000,9.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,92.100000

# Seprate datasets dependent and independent variable

In [5]:
X=df[['Math_Marks','Science_Marks','English_Marks','Hindi_Marks','SST_Marks']]
y=df['Final_Score']

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test=train_test_split(X,y, test_size=0.2, random_state=42)

In [7]:
from sklearn.linear_model import Lasso
ls=Lasso()
ls.fit(X_train, y_train)

Lasso()

In [8]:
y_pred=ls.predict(X_test)
y_pred

array([57.2071383 , 67.11963788, 73.79662004, ..., 56.6472126 ,
       71.20280243, 56.22732913], shape=(2000,))

In [9]:
from sklearn.metrics import r2_score
r2=r2_score(y_test, y_pred)
r2

0.999973948082083

In [10]:
import pickle
pickle.dump(ls,open("stmp2.pkl","wb"))
print("pickle file is saved")

pickle file is saved